# This is a basic workflow to help you get started with Actions

name: validation With GitHub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
   pull_request:
    branches: [ "main" ]
 

  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
    # Checking Version 
      - name: Setup Node
        uses: actions/setup-node@v1
        with: 
              node-version: 14

      # Runs a single command using the runners shell
      - name: Install SFDX CLI
        run: npm install sfdx-cli --global
      # Connecting to SF Org
      - name: Integrating Salesforce 
        run : sfdx force:auth:jwt:grant --clientid 3MVG9pRzvMkjMb6mQmwyTIqGh0POKHjFRtQ1jdeZ5mIkb7tIZghEBH45Ya3G1C2GR.qlVEmVfwY9xkzdAPa1j --jwtkeyfile ./buildfile/server.key --username ronnieneworg@gmail.com --instanceurl https://login.salesforce.com
      # Runs a set of commands using the runners shell
      - name: Run a single-line script
        run: 
          echo Installed SFDX CLI and npm
        # Convert to Deploy Source

      - name: Convert to Deploy Source

        run: sfdx force:source:convert -r ./force-app -d ./toDeploy
  
    

    # Run Validation of Deploy Source

      - name: Run Validation on Deploy Source

        run: sfdx force:source:deploy -c -x manifest/package.xml -u ronnieneworg@gmail.com
    
